#!/usr/bin/env python3
"""VM-only, stdin-only Telegram configuration helper.

The local setup scripts send a JSON payload over an SSH pipe. Tokens are never
placed in Terraform variables, OCI user-data, command-line arguments, or logs.
"""
from __future__ import annotations

import json
import os
import re
import sys
import stat
from pathlib import Path

TOKEN_RE = re.compile(r"^[0-9]+:[A-Za-z0-9_-]+$")
USER_RE = re.compile(r"^[0-9]+$")


def secure_write(path: Path, content: str) -> None:
    path.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def update_env(path: Path, values: dict[str, str]) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    for key, value in values.items():
        lines = [line for line in lines if not line.startswith(f"{key}=")]
        lines.append(f"{key}={value}")
    secure_write(path, "\n".join(lines).rstrip() + "\n")


def validate_token(value: object, name: str) -> str:
    if not isinstance(value, str) or not value:
        return ""
    if not TOKEN_RE.fullmatch(value):
        raise ValueError(f"{name} has an invalid Telegram token format")
    return value


def main() -> None:
    payload = json.load(sys.stdin)
    users = payload.get("allowed_users", [])
    if not isinstance(users, list) or not users or any(
        not isinstance(user, (int, str)) or not USER_RE.fullmatch(str(user)) for user in users
    ):
        raise ValueError("allowed_users must contain at least one numeric Telegram user ID")
    allowed = ",".join(str(user) for user in users)
    hermes_token = validate_token(payload.get("hermes_bot_token", ""), "hermes_bot_token")
    cc_token = validate_token(payload.get("cc_connect_bot_token", ""), "cc_connect_bot_token")
    if not hermes_token and not cc_token:
        print("No Telegram tokens supplied; integrations remain disabled.")
        return

    home = Path.home()
    configured = []
    if hermes_token:
        update_env(
            home / ".hermes" / ".env",
            {
                "TELEGRAM_BOT_TOKEN": hermes_token,
                "TELEGRAM_ALLOWED_USERS": allowed,
            },
        )
        configured.append("Hermes")

    if cc_token:
        config_path = home / ".cc-connect" / "config.toml"
        if not config_path.exists():
            workspace = home / "agent-workspace"
            workspace.mkdir(mode=0o700, parents=True, exist_ok=True)
            config = f'''# Generated by oci-agent-vm. Edit with cc-connect's Web UI if needed.\n\n[[projects]]\nname = "personal-agent"\nadmin_from = "{allowed}"\n\n[projects.agent]\ntype = "pi"\n\n[projects.agent.options]\nwork_dir = "{workspace}"\nmode = "default"\n\n[[projects.platforms]]\ntype = "telegram"\n\n[projects.platforms.options]\ntoken = "{cc_token}"\nallow_from = "{allowed}"\n'''
            secure_write(config_path, config)
            configured.append("cc-connect")
        else:
            configured.append("cc-connect (existing config left unchanged)")

    print("Configured Telegram: " + ", ".join(configured))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"Telegram configuration failed: {exc}") from exc
